server:
  http:
    addr: 127.0.0.1:8000
    timeout: 10s
    corsAllowOrigins: ["*"]
  grpc:
    addr: 127.0.0.1:8001
    timeout: 10s
  stats:
    addr: ""
data:
  database:
    maxOpenConns: 100
    maxIdleConns: 10
    connMaxLifetime: 60
    driver: sqlite
    dsn: ./data/universer.sqlite
  rabbitmq:
    enabled: false
  redis:
    addr: 127.0.0.1:6379
    db: 0
    password: ""
    read_timeout: 1s
    username: ""
    write_timeout: 1s
  s3:
    accessKeyID: minioadmin
    accessKeySecret: minioadmin
    region: us-east-1
    endpoint: http://127.0.0.1:9000
    usePathStyle: true
    presignExpires: 3600s
    defaultBucket: univer
service:
  apply:
    addr: "127.0.0.1:5002"
    timeout: 10s
  fileExchange:
    addr: "127.0.0.1:5002"
    timeout: 10s
apiLimit:
  ip: {}
  method:
    interval: 30s
    tokens: 600
  perMethod:
    /universer.v1.SurveyService/CaptureEvent:
      interval: 30s
      tokens: 1500
  perMethodIp:
    /universer.v1.LicenseService/DeployAccess:
      interval: 30s
      tokens: 300
  perMethodUser: {}
  user:
    interval: 30s
    tokens: 300
admin: []
extra:
  celldataMaxSize: 10485760 # 单位字节，10M
auth:
  enabled: true
  anonymous:
    enabled: true
  permission:
    customerStrategies: ""
    defaultShareRole: editor
    defaultShareScope: public
    enableObjInherit: true
    enabled: true
usip:
  enabled: false
  uri:
    collaborators: http://usip:8080/collaborators
    credential: http://usip:8080/credential
    role: http://usip:8080/role
    userinfo: http://usip:8080/userinfo
sentryConfig:
  dsn: ""
  debug: false
  enableTracing: true
  TracesSampleRate: 1.0
dataProtectionConf:
  enableProtection: false
  dataKeyRotate: 5s
  dataKeyCacheExpiration: 30s
sesConfig: {}
postHogConf:
  enabled: false
  endpoint: 
  projectKey: 
entitlementConf:
  enable: false
workspace:
  enabled: false
statsConf:
  maxRecords: 10000
  timeInterval: 10
